server:
  error:
    include-exception: false
    include-stacktrace: never
    include-binding-errors: never
    include-message: always

spring:
  datasource:
    url: jdbc:mysql://db-blog:3306/blog?useSSL=false&useUnicode=true&charset=utf8mb4&characterEncoding=utf8&serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true
    username: api-blog
