spring:
  datasource:
    url: jdbc:mysql://db-blog:3306/blog?useSSL=false&useUnicode=true&charset=utf8mb4&characterEncoding=utf8&serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true
    username: api_blog
