springdoc:
  swagger-ui:
    path: /doc
    disable-swagger-default-url: true

spring:
  datasource:
    url: jdbc:h2:file:~/data/blog;NON_KEYWORDS=USER
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true

jwt:
  secret: CNFjvDbu42BaFPmpDgjw7yFzg0yqms8l
